### ISSUE TITLE
Update unit tests to use CentOS 6.7

### ISSUE THREAD

**Issue by kgeorgak** [rackspace-cookbooks/user_shadow#6]
We need to wait for a solution to https://github.com/customink/fauxhai/issues/163 first

**Comment by martinb3** [comment]
Updated link in description to link directly to the issue.

**Comment by martinb3** [comment]
Fauxhai issue is resolved in https://github.com/customink/fauxhai/pull/164. This issue should be unblocked.

**Comment by kgeorgak** [comment]
Fixed in #11
